version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # - npm i
      # - npm run lint
  pre_build:
    commands:
      - echo Build
      - npm install
  build:
    commands:
      - npm run build
      # we could copy builded data here instead of the next Deploy step in codepipeline
      # - aws s3 sync --delete ./${dist_dir} s3://${bucket_name} --cache-control max-age=3600

artifacts:
  files:
    - "**/*"
  name: "web-dist-${env}"
  base-directory: ${dist_dir}
